# Generated by Django 4.2.3 on 2023-10-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sage',
            new_name='stage',
        ),
    ]
